#!/bin/bash
# ==============================================================================
# NEOS PLATFORM - SHARED INFRASTRUCTURE RESTORATION SCRIPT
# ==============================================================================
# This script restores the Postgres databases, Redis cache, and MinIO data
# from a compressed backup archive generated by backup.sh.
#
# Usage: ./restore.sh /path/to/backup/neos_backup_YYYY-MM-DD_HHMMSS.tar.gz

set -e
set -o pipefail

# 1. Check arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 <path_to_backup_archive.tar.gz>"
    exit 1
fi

BACKUP_ARCHIVE="$1"

if [ ! -f "$BACKUP_ARCHIVE" ]; then
    echo "Error: Backup archive file not found: $BACKUP_ARCHIVE"
    exit 1
fi

# 2. Load configuration from root environment file
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    export $(grep -v '^#' "$ENV_FILE" | xargs)
else
    echo "Error: .env file not found at $ENV_FILE. Cannot run restoration."
    exit 1
fi

TEMP_DIR="$REPO_DIR/backups/tmp/restore_$(date +%s)"
mkdir -p "$TEMP_DIR"

# Cleanup temporary files on exit
function cleanup {
    echo "Cleaning up temporary restore files..."
    rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

echo "=== Starting Restoration from $BACKUP_ARCHIVE ==="

# Extract backup package to temp folder
echo "Extracting backup archive..."
tar -xzf "$BACKUP_ARCHIVE" -C "$TEMP_DIR" --strip-components=1

# Get extracted session directory name
SESSION_DIR=$(find "$TEMP_DIR" -maxdepth 1 -type d -name "backup_*" | head -n 1)

if [ -z "$SESSION_DIR" ]; then
    echo "Error: Failed to locate extracted session directory inside backup."
    exit 1
fi

# Ask for confirmation before modifying production files
read -p "WARNING: This will overwrite existing databases, cache, and object storage. Are you sure you want to proceed? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Restoration cancelled by user."
    exit 1
fi

# ------------------------------------------------------------------------------
# 1. Restore PostgreSQL Databases
# ------------------------------------------------------------------------------
echo "--- Restoring PostgreSQL Databases ---"
if [ -n "${POSTGRES_MULTIPLE_DATABASES:-}" ]; then
    IFS=',' read -ra DB_LIST <<< "$POSTGRES_MULTIPLE_DATABASES"
    for db_entry in "${DB_LIST[@]}"; do
        db_entry=$(echo "$db_entry" | xargs)
        if [ -n "$db_entry" ]; then
            IFS=':' read -ra DB_PARTS <<< "$db_entry"
            db_name="${DB_PARTS[0]}"
            db_user="${DB_PARTS[1]}"
            
            DB_DUMP="$SESSION_DIR/postgres_$db_name.sql.gz"
            if [ -f "$DB_DUMP" ]; then
                echo "Restoring database '$db_name'..."
                
                # Terminate active database connections
                docker exec -t neos_postgres psql -U "$POSTGRES_SUPERUSER" -c \
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '$db_name' AND pid <> pg_backend_pid();" || true
                
                # Recreate database to ensure clean schema
                docker exec -t neos_postgres psql -U "$POSTGRES_SUPERUSER" -c "DROP DATABASE IF EXISTS $db_name;"
                docker exec -t neos_postgres psql -U "$POSTGRES_SUPERUSER" -c "CREATE DATABASE $db_name OWNER $db_user;"
                
                # Load dump file
                gunzip -c "$DB_DUMP" | docker exec -i neos_postgres psql -U "$POSTGRES_SUPERUSER" -d "$db_name"
                echo "Database '$db_name' successfully restored."
            else
                echo "Warning: Database dump for '$db_name' not found in backup. Skipping."
            fi
        fi
    done
else
    # Simple restore for default DB
    DB_DUMP="$SESSION_DIR/postgres_main.sql.gz"
    if [ -f "$DB_DUMP" ]; then
        echo "Restoring main database..."
        gunzip -c "$DB_DUMP" | docker exec -i neos_postgres psql -U "$POSTGRES_SUPERUSER" -d "$POSTGRES_SUPERUSER"
    fi
fi

# ------------------------------------------------------------------------------
# 2. Restore Redis Cache
# ------------------------------------------------------------------------------
REDIS_DUMP="$SESSION_DIR/redis_dump.rdb"
if [ -f "$REDIS_DUMP" ]; then
    echo "--- Restoring Redis Cache ---"
    echo "Stopping Redis service..."
    docker compose stop cache
    
    # Run Alpine container to wipe and copy dump.rdb and appendonlydir in the volume
    docker run --rm \
      -v neos_redis_data:/redis_data \
      -v "$SESSION_DIR":/backup_src \
      alpine sh -c "rm -rf /redis_data/dump.rdb /redis_data/appendonlydir && cp /backup_src/redis_dump.rdb /redis_data/dump.rdb && (cp -R /backup_src/redis_appendonlydir /redis_data/appendonlydir 2>/dev/null || true)"
      
    echo "Starting Redis service..."
    docker compose start cache
    echo "Redis cache successfully restored."
else
    echo "Warning: Redis dump not found in backup. Skipping."
fi

# ------------------------------------------------------------------------------
# 3. Restore MinIO Object Storage
# ------------------------------------------------------------------------------
MINIO_ARCHIVE="$SESSION_DIR/minio_data.tar.gz"
if [ -f "$MINIO_ARCHIVE" ]; then
    echo "--- Restoring MinIO Object Storage ---"
    echo "Stopping MinIO service..."
    docker compose stop object-store
    
    echo "Replacing MinIO data..."
    # Wipe existing volume and extract archive in volume
    docker run --rm \
      -v neos_minio_data:/minio_data \
      -v "$SESSION_DIR":/backup_src \
      alpine sh -c "rm -rf /minio_data/* && tar -xzf /backup_src/minio_data.tar.gz -C /minio_data"
      
    echo "Starting MinIO service..."
    docker compose start object-store
    echo "MinIO object storage successfully restored."
else
    echo "Warning: MinIO archive not found in backup. Skipping."
fi

echo "=== Restoration Completed Successfully at $(date) ==="
