_format_version: "1.1"

plugins:
  - name: cors
    config:
      origins:
        - "https://webapp.neosfacility.com"
        - "https://dashboard.neosfacility.com"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Authorization
        - Content-Type
        - apikey
        - x-client-info
        - Accept
        - X-Requested-With
        - authorization
        - content-type
        - X-Client-Info
        - ApiKey
        - x-supabase-api-version
        - X-Supabase-Api-Version
        - accept-profile
        - Accept-Profile
        - prefer
        - Prefer
        - Range
        - range
        - Content-Range
        - content-range
        - Profile-Options
        - profile-options
      exposed_headers:
        - x-supabase-info
        - Content-Range
      credentials: true
      max_age: 3600
      preflight_continue: false

services:
  # 1. Supabase Auth Routing
  - name: auth
    url: http://supabase-auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: true

  # 2. Supabase PostgREST Schema REST routing
  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
        strip_path: true

  # 3. Supabase Elixir Realtime WebSocket routing
  - name: realtime
    url: http://supabase-realtime:4000
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1
        strip_path: true

  # 4. Supabase storage proxy routing
  - name: storage
    url: http://supabase-storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1
        strip_path: true
